#!/usr/bin/python
#################################################################################################
# Title:   Namechooser4000.py
# Description:
#  This script is made to select a random winner of the Oslo site Julekalender.
#  The random number is generated by measuring the quantum mechanical effects on photons travelling through a vacuum.
#  More detail on the physics here: qrng.anu.edu.au
#################################################################################################

import sys
import time
import json
import itertools
import threading
import subprocess
import RPi.GPIO as GPIO
from urllib import urlencode

from urllib2 import urlopen

# Only as backup due to unstable wifi-connection
import random

choose_name_button_pin = 37
save_name_button_pin = 36
URL = 'https://qrng.anu.edu.au/API/jsonI.php'
# TODO: In the future, this will be deprecated. Migrate to: https://quantumnumbers.anu.edu.au/

GPIO.setmode(GPIO.BOARD)
GPIO.setup(choose_name_button_pin, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(save_name_button_pin, GPIO.IN, pull_up_down=GPIO.PUD_UP)

keep_spinning = True
keep_checking = True
error_message = None

numbers = None


def spin_bar():
    """
    Spin a terminal spinner while waiting for QRNG data
    """
    spinner = itertools.cycle(['-', '\\', '|', '/'])
    while keep_spinning:
        sys.stdout.write(next(spinner))
        sys.stdout.flush()
        time.sleep(0.1)
        sys.stdout.write('\b')


def get_random_number():
    """Fetch data from the ANU Quantum Random Numbers JSON API"""
    global numbers, keep_checking, error_message
    if numbers:
        return
    url = URL + '?' + urlencode({
        'type': 'uint16',
        'length': 30,
        'size': 1,
    })
    try:
        keep_checking = True
        data = urlopen(url, timeout=5).read()
        data = json.loads(data)
        assert data['success'] is True
        numbers = data['data']
        error_message = None
    except Exception:
        error_message = "\nError in getting quantum random numbers. Using Pseudo-random fallback..."
    keep_checking = False


def qrng_uniform_index(n):
    """Return an unbiased integer in [0, n-1] using rejection sampling from the QRNG."""
    # Use 16-bit chunks from the QRNG. If n > 2^16, combine into 32-bit.
    global keep_checking
    bound = 2 ** 16
    limit = (bound // n) * n
    while keep_checking:
        pass
    while numbers:
        # Fallback to pseudo-random
        x = numbers.pop()
        if x < limit:
            return x % n
    return random.randint(0,n)


def print_winners():
    """Print the winner's name using figlet"""
    with open('already_won_names.txt') as winners:
        print("\nThis year's current winners:")
        print(winners.read())

if __name__ == "__main__":
    subprocess.call(['figlet', '-c', 'Namechooser\n4000'])
    print_winners()

    rnm = None
    while True:
        # Wait for button press to choose name
        while GPIO.input(choose_name_button_pin):
            # Use GPIO pin to chose if you want to save name already picked
            if not GPIO.input(save_name_button_pin) and rnm is not None:
                with open('already_won_names.txt', 'a') as already_won_names:
                    already_won_names.write(rnm + '\n')
                print("Name saved!")
                print_winners()
                time.sleep(0.5)
                rnm = None
        # Load names and prepare ticket pool with 3 tickets per person
        original_names = [line.rstrip() for line in open('names.txt')]
        names = original_names * 3

        # Remove tickets from people who have already won
        with open('already_won_names.txt') as already_won_names:
            for name in already_won_names:
                try:
                    names.remove(name.rstrip())
                except ValueError:
                    pass

        keep_spinning = True
        sys.stdout.write("Splitting photon beam... ")

        t = threading.Thread(target=spin_bar)
        t.start()
        # Get random index from QRNG and select name
        sys.stdout.write("\r    Randomizing names...   ")
        t2 = threading.Thread(target=get_random_number)
        t2.start()
        for name in original_names:
            sys.stdout.write("\r{:>23}...  ".format(name))
            time.sleep(0.1)
        if error_message:
            print(error_message)


        idx = qrng_uniform_index(len(names))
        rnm = names[idx]
        time.sleep(0.1)

        keep_spinning = False

        # Print the winner using figlet
        print("\r                                    \n")
        subprocess.call(['figlet', '-c', rnm.decode('utf-8').encode('latin-1')])

        print("\n\n")
